colour = input('Enter your colour:')
age= input('Enter your age:')
name = input('Enter your name:')
print()
print()
print('Hey your favaroute colur is ' + colour)
print('SO I THINK YOUR NAME COULD BE '+ name + ' ! ')
print('And if I am not wrong , then your age is ' + age)
print()
print()
print('Aint i detective James Bond !!!')